services:
  ubuntu-core:
    image: ubuntu-core:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ./config/.kube:/root/.kube
      - ~/.minikube:/root/.minikube
    privileged: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped
    container_name: ubuntu-core
    working_dir: /app
    tty: true
    stdin_open: true
    network_mode: "host"
