services:
  ubuntu-core:
    image: ubuntu-core:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    privileged: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped
    container_name: ubuntu-core
    working_dir: /app
    tty: true
    stdin_open: true
    networks:
      - ubuntu-core-network

networks:
  ubuntu-core-network:
    driver: bridge
